#define BAM_VERSION_MAJOR "0"
#define BAM_VERSION_MINOR "5"
#define BAM_VERSION_PATCH "1"
#define BAM_VERSION_STRING BAM_VERSION_MAJOR "." BAM_VERSION_MINOR
#define BAM_VERSION_STRING_COMPLETE BAM_VERSION_MAJOR "." BAM_VERSION_MINOR "." BAM_VERSION_PATCH
	
